title: Maciej Piechota cuisine
description: "About security, penetration testing, python"
image: /assets/haqpl.png
author:
  name: "Maciej Piechota"
  email: "piechotamaciej@gmail.com"
  url: "https://haqpl.github.io"
  twitter: haqpl
  image: /assets/haqpl.png
  
twitter:
  username: haqpl

baseurl: /
disqus: haqpl-blog
google_analytics: UA-137044900-1

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
defaults:
  - scope:
      path: ""
    values:
      image: /assets/haqpl.png

social:
  links:
    - https://twitter.com/haqpl
    - https://www.linkedin.com/in/0x31337
    - https://github.com/haqpl


future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-mentions

# Custom variables
owner : "Maciej Piechota"
year : "2019"

