title: Maciej Piechota blog site
description: "About web security and conquering the world"
author:
  name: "Maciej Piechota"
  email: "piechotamaciej@gmail.com"
  url: "https://haqpl.github.io"

baseurl: /
disqus: haqpl-blog


source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Maciej Piechota"
year : "2019"
